use super::*;

/// Custom section name for AOT data that the deploy side finds by
/// section name. Mach-O takes `segment,section`; COFF gets the 8-byte
/// name because the final PE keeps only short names; ELF takes the
/// name as is.
pub(super) fn aot_data_section(
    triple: &target_lexicon::Triple,
    name: &str,
    coff_name: &str,
) -> String {
    match triple.binary_format {
        target_lexicon::BinaryFormat::Macho => format!("__DATA,{name}"),
        target_lexicon::BinaryFormat::Coff => coff_name.to_owned(),
        _ => name.to_owned(),
    }
}

/// produce a `Value` of type
/// `I64` whose runtime contents are the live `Gc<LuaStr>` pointer for
/// `key_v`. Used by the four `iconst(I64, key.as_ptr() as i64)` sites
/// that feed `luna_jit_*_field` / `luna_jit_get_tab_up` helpers.
///
/// JIT path (`opts.aot == false`): emits `iconst(I64, key.as_ptr())`,
/// byte-for-byte identical to what the lowerer used to emit inline.
///
/// AOT path (`opts.aot == true`): declares two stably-named data
/// objects (deduped across calls via Cranelift's
/// `Module::declare_data` name interning):
///
/// - `__luna_aot_strkey_slot_<hex>` — 8-byte writable slot, defined
///   if not already defined this lower call, zero-initialised. Holds
///   the resolved `Gc<LuaStr>::as_ptr()` after the deploy-side
///   startup hook runs.
/// - `__luna_aot_strkey_bytes_<hex>` — read-only data carrying the
///   UTF-8 bytes the deploy `Vm` must intern.
///
/// `<hex>` is a 16-char SHA-256 prefix over the bytes (collision
/// risk: ~1 in 2^64 across the unique-string-key population of any
/// realistic Lua program). The bytes object is what the deploy-side
/// resolver walks; the slot is what the IR loads through.
///
/// Returns a `Value` holding the loaded `Gc<LuaStr>` pointer, suitable
/// for passing as the `key_arg` parameter to `luna_jit_set_field` /
/// `_get_field` / `_get_tab_up`.
pub(super) fn emit_str_key_arg<E: Emit>(
    bcx: &mut E,
    key_v: luna_core::runtime::Gc<luna_core::runtime::LuaStr>,
    aot: bool,
    defined_aot_data: &mut std::collections::HashSet<DataId>,
) -> Value {
    if !aot {
        return bcx.ins().iconst(types::I64, key_v.as_ptr() as i64);
    }
    let bytes = key_v.as_bytes();
    let hex = strkey_hex_label(bytes);

    // deploy-side resolver hook.
    //
    // In addition to the (slot, bytes) pair, we emit a third *index*
    // data symbol per unique key: 16 bytes of `[bytes_addr, slot_addr]`,
    // both populated by static-linker relocations. All index entries
    // land in a dedicated `__luna_aot_strkey_idx` section, so the
    // deploy resolver in `luna-runtime-helpers::luna_aot_run` can
    // walk the whole-program index between linker-provided start/end
    // bracket symbols (no per-binary enumeration scheme needed).
    //
    // Bracket symbol convention (declared on the resolver side):
    //   - ELF / lld: `__start_luna_strkey_idx` /
    //                `__stop_luna_strkey_idx` — auto-generated by the
    //                linker because the section name is a valid C
    //                identifier.
    //   - Mach-O:    `section$start$__DATA$luna_strkey_idx` /
    //                `section$end$__DATA$luna_strkey_idx` —
    //                Apple `ld`'s magic section-bracket synthesizer.
    //
    // Section name capped at 15 chars for the Mach-O 16-byte sectname
    // field (one slot for the implicit NUL when comparing).

    // 8-byte writable slot — IR loads through it.
    let slot_name = format!("__luna_aot_strkey_slot_{hex}");
    let slot_id = bcx
        .declare_data(&slot_name, Linkage::Export, true, false)
        .expect("declare_data slot");
    if defined_aot_data.insert(slot_id) {
        let mut desc = DataDescription::new();
        desc.define(Box::new([0u8; 8]));
        // `define_data` errors on redefinition — `insert` guards us.
        // Best-effort: ignore the error path (the only way `define`
        // fails here is duplicate-define, which our HashSet prevents).
        let _ = bcx.define_data(slot_id, &desc);
    }

    // Bytes manifest — deploy-side resolver reads via the index
    // section. Layout: little-endian u64 length, then the raw bytes
    // (no NUL). Read-only, non-TLS.
    let bytes_name = format!("__luna_aot_strkey_bytes_{hex}");
    let bytes_id = bcx
        .declare_data(&bytes_name, Linkage::Export, false, false)
        .expect("declare_data bytes");
    if defined_aot_data.insert(bytes_id) {
        let mut payload = Vec::with_capacity(8 + bytes.len());
        payload.extend_from_slice(&(bytes.len() as u64).to_le_bytes());
        payload.extend_from_slice(bytes);
        let mut desc = DataDescription::new();
        desc.define(payload.into_boxed_slice());
        let _ = bcx.define_data(bytes_id, &desc);
    }

    // Index entry — one per unique strkey, 16 bytes of
    // `[bytes_addr, slot_addr]` resolved by the static linker. Stable
    // name (`_idx_<hex>`) so multiple lower_trace_into calls within
    // one module don't emit duplicate entries (the resolver would
    // tolerate duplicates — re-intern is idempotent — but the link
    // bloat is wasted bytes).
    //
    // `Linkage::Local` because:
    //   - The symbol name is only an internal handle for the dedup
    //     guard; nothing outside this lowerer references it by name.
    //   - The deploy-side resolver walks the section, not by name.
    //   - Local keeps the global symbol table small.
    //
    // The dedicated `__luna_aot_strkey_idx` section lets the linker
    // auto-bracket the whole-program range; placing the entries in
    // the default rodata section would require an enumeration scheme
    // (per-`.o` registry table or `nm` parsing at startup).
    let idx_name = format!("__luna_aot_strkey_idx_{hex}");
    let idx_id = bcx
        .declare_data(&idx_name, Linkage::Local, false, false)
        .expect("declare_data idx");
    if defined_aot_data.insert(idx_id) {
        let mut desc = DataDescription::new();
        desc.define(Box::new([0u8; 16]));
        // Mach-O caps section names at 16 chars; `luna_strkey_idx`
        // is 15. ELF / COFF have no such limit but accept the same
        // short name — the deploy resolver brackets by the literal
        // section name on both platforms.
        // On Mach-O the section must be in `__DATA` so it merges with
        // the cmain shim's `__DATA,luna_strkey_idx` placeholder; in any
        // other segment the deploy resolver's
        // `section$start$__DATA$luna_strkey_idx` brackets only the
        // placeholder and misses every real entry.
        //
        // PE section headers are fixed 8 bytes, and `link.exe` /
        // `lld-link` drop the COFF long-name string table when
        // producing the final PE, so COFF uses the short name
        // `.lt_skix` (matches the C placeholder in
        // `luna-aot::embed::write_aot_cmain_object_for` and the
        // deploy-side `windows_section::find_section` needle).
        desc.set_custom_section(&aot_data_section(
            &bcx.target_triple(),
            "luna_strkey_idx",
            ".lt_skix",
        ));
        // 8-byte alignment for the two pointer relocations at offsets
        // 0 and 8. Mach-O `ld` hard-rejects unaligned pointer slots
        // ("pointer not aligned in `___luna_aot_strkey_idx_…`+0x8"),
        // which fires the first time a trace AOT-compiles a GetField/
        // SetField op (the strkey idx didn't exist in the trivial
        // smoke source).
        desc.set_align(8);
        // Two pointer-sized relocations: linker fills 0..8 with the
        // resolved address of `bytes_id` and 8..16 with `slot_id`.
        let bytes_gv = bcx.declare_data_in_data(bytes_id, &mut desc);
        let slot_gv = bcx.declare_data_in_data(slot_id, &mut desc);
        desc.write_data_addr(0, bytes_gv, 0);
        desc.write_data_addr(8, slot_gv, 0);
        let _ = bcx.define_data(idx_id, &desc);
    }

    // Emit the load through the slot.
    let slot_gv = bcx.declare_data_in_func(slot_id);
    let slot_addr = bcx.symbol_value(types::I64, slot_gv);
    bcx.ins()
        .load(types::I64, MemFlagsData::trusted(), slot_addr, 0)
}

/// Stable 16-hex-char label for a string key. Pure FNV-1a 64-bit so we
/// don't pull `sha2` (luna-core 0-third-party-dep contract — this code
/// is in luna-jit, but the encoding stability matters for the
/// deploy-side resolver and a 64-bit FNV is collision-safe enough at
/// the trace-key scale).
pub(super) fn strkey_hex_label(bytes: &[u8]) -> String {
    let mut h: u64 = 0xcbf29ce484222325;
    for &b in bytes {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    format!("{h:016x}")
}

/// produce a `Value` of type `I64`
/// whose runtime contents are a pointer to the first
/// `FrameMaterializeInfo` of an inline cmp@d>0 side-exit's frame chain.
/// Used by the two `iconst(I64, Rc::as_ptr(&chain_rc) as ...)` sites
/// that feed `luna_jit_trace_materialize_frames(n, ptr)`.
///
/// JIT path (`opts.aot == false`): emits `iconst(I64, chain_first_ptr)`,
/// byte-for-byte identical to what the lowerer used to emit inline. The
/// caller still holds `chain_rc` alive via `per_exit_inline_vec`, so
/// the baked address is valid for the trace's mmap lifetime.
///
/// AOT path (`opts.aot == true`): declares three stably-named data
/// symbols (deduped by FNV-1a-64 of the packed chain bytes):
///
/// - `__luna_aot_inline_chain_slot_<hex>` — 8-byte writable u64,
///   zero-initialised. Deploy-side resolver writes the reconstructed
///   chain's first-element pointer here BEFORE any AOT trace dispatches.
/// - `__luna_aot_inline_chain_bytes_<hex>` — read-only, packed
///   `FrameMaterializeInfo` records: `[u64 count, (base_offset u32, pc
///   u32, nresults i32) * count]`. Same packing as the v3 wire-format
///   [`PerExitInlineEntry::chain_bytes`] field plus an 8-byte count
///   prefix so the resolver can size its reconstruction.
/// - `__luna_aot_inline_chain_idx_<hex>` — 16-byte `[bytes_ptr,
///   slot_ptr]` resolved by the static linker into the
///   `luna_inline_chain_idx` section so the deploy-side resolver can
///   walk every entry without per-binary enumeration.
///
/// IR emits `symbol_value(slot) + load(I64)`. The deploy resolver
/// (`luna-runtime-helpers::aot_inline_chain_resolver`) walks the idx
/// section, rebuilds a `Vec<FrameMaterializeInfo>` from the bytes
/// payload, materialises it as an `Rc<[...]>` whose ownership is
/// leaked into a process-lifetime store, then writes
/// `Rc::as_ptr() as *const FrameMaterializeInfo` into the slot. The
/// resolver runs BEFORE `aot_trace_registry::install_all` so the slot
/// is populated by the time `luna_jit_trace_materialize_frames` is
/// called from AOT mcode.
///
/// `<hex>` is FNV-1a-64 over the packed bytes (no count prefix in the
/// hash input — only the records). Collision risk: ~1 in 2^64 over
/// realistic trace populations.
pub(super) fn emit_chain_ptr_arg<E: Emit>(
    bcx: &mut E,
    chain: &[FrameMaterializeInfo],
    chain_rc_first_ptr: i64,
    aot: bool,
    defined_aot_data: &mut std::collections::HashSet<DataId>,
) -> Value {
    if !aot {
        return bcx.ins().iconst(types::I64, chain_rc_first_ptr);
    }
    // Pack the chain identically to the v3 wire format's chain_bytes:
    // three little-endian 32-bit fields per record. Drives both the
    // FNV hash (so identical chains share symbols across traces) and
    // the read-only bytes payload the resolver consumes.
    let mut packed: Vec<u8> = Vec::with_capacity(chain.len() * 12);
    for fm in chain {
        packed.extend_from_slice(&fm.base_offset.to_le_bytes());
        packed.extend_from_slice(&fm.pc.to_le_bytes());
        packed.extend_from_slice(&fm.nresults.to_le_bytes());
    }
    let hex = strkey_hex_label(&packed);

    // Writable 8-byte slot — IR loads through it. Zero at link time;
    // the deploy resolver populates with the rebuilt chain's pointer.
    let slot_name = format!("__luna_aot_inline_chain_slot_{hex}");
    let slot_id = bcx
        .declare_data(&slot_name, Linkage::Export, true, false)
        .expect("declare_data inline chain slot");
    if defined_aot_data.insert(slot_id) {
        let mut desc = DataDescription::new();
        desc.define(Box::new([0u8; 8]));
        let _ = bcx.define_data(slot_id, &desc);
    }

    // Bytes payload — `[u64 count, packed records]`, read-only. Count
    // prefix lets the resolver size its reconstruction without holding
    // an out-of-band length table.
    let bytes_name = format!("__luna_aot_inline_chain_bytes_{hex}");
    let bytes_id = bcx
        .declare_data(&bytes_name, Linkage::Export, false, false)
        .expect("declare_data inline chain bytes");
    if defined_aot_data.insert(bytes_id) {
        let mut payload = Vec::with_capacity(8 + packed.len());
        payload.extend_from_slice(&(chain.len() as u64).to_le_bytes());
        payload.extend_from_slice(&packed);
        let mut desc = DataDescription::new();
        desc.define(payload.into_boxed_slice());
        let _ = bcx.define_data(bytes_id, &desc);
    }

    // Index entry — one per unique chain, 16 bytes of
    // `[bytes_addr, slot_addr]` resolved by the static linker. Lives in
    // a dedicated `luna_inline_chain_idx` (Mach-O/ELF) / `.lt_chai`
    // (Windows COFF, 8-byte short-name limit) section so the deploy
    // resolver brackets the whole-program range.
    let idx_name = format!("__luna_aot_inline_chain_idx_{hex}");
    let idx_id = bcx
        .declare_data(&idx_name, Linkage::Local, false, false)
        .expect("declare_data inline chain idx");
    if defined_aot_data.insert(idx_id) {
        let mut desc = DataDescription::new();
        desc.define(Box::new([0u8; 16]));
        // Mach-O sectname max is 16 chars; `luna_inline_chain_idx`
        // is 21 — too long. Use the same 15-char `luna_inline_chnx`
        // shape (under the cap). Windows COFF short name 8-char cap →
        // `.lt_chai`. Both names must match the deploy resolver's
        // bracket / section-walker needles.
        desc.set_custom_section(&aot_data_section(
            &bcx.target_triple(),
            "luna_inline_chnx",
            ".lt_chai",
        ));
        desc.set_align(8);
        let bytes_gv = bcx.declare_data_in_data(bytes_id, &mut desc);
        let slot_gv = bcx.declare_data_in_data(slot_id, &mut desc);
        desc.write_data_addr(0, bytes_gv, 0);
        desc.write_data_addr(8, slot_gv, 0);
        let _ = bcx.define_data(idx_id, &desc);
    }

    // Emit the load through the slot.
    let slot_gv = bcx.declare_data_in_func(slot_id);
    let slot_addr = bcx.symbol_value(types::I64, slot_gv);
    bcx.ins()
        .load(types::I64, MemFlagsData::trusted(), slot_addr, 0)
}

/// The pointer of `proto`, which an inlined call checks the callee's
/// function against. JIT: the live pointer (the trace keeps the proto
/// alive, see `CompiledTrace::inlined_protos`). AOT: a load through
/// `__luna_aot_proto_slot_<hash>`, which the deploy side fills with the
/// loaded chunk's proto of the same `Proto::stable_hash`; an index entry
/// `[hash_addr, slot_addr]` in section `luna_proto_idx` (COFF `.lt_prix`)
/// lets it find every slot.
pub(super) fn emit_proto_arg<E: Emit>(
    bcx: &mut E,
    proto: luna_core::runtime::Gc<luna_core::runtime::function::Proto>,
    aot: bool,
    defined_aot_data: &mut std::collections::HashSet<DataId>,
) -> Value {
    if !aot {
        return bcx.ins().iconst(types::I64, proto.as_ptr() as i64);
    }
    let hash = proto.stable_hash();
    let hex: String = hash.iter().map(|b| format!("{b:02x}")).collect();
    let slot_id = bcx
        .declare_data(
            &format!("__luna_aot_proto_slot_{hex}"),
            Linkage::Export,
            true,
            false,
        )
        .expect("declare_data proto slot");
    if defined_aot_data.insert(slot_id) {
        let mut desc = DataDescription::new();
        desc.define(Box::new([0u8; 8]));
        let _ = bcx.define_data(slot_id, &desc);
    }
    let hash_id = bcx
        .declare_data(
            &format!("__luna_aot_proto_hash_{hex}"),
            Linkage::Export,
            false,
            false,
        )
        .expect("declare_data proto hash");
    if defined_aot_data.insert(hash_id) {
        let mut desc = DataDescription::new();
        desc.define(Box::new(hash));
        let _ = bcx.define_data(hash_id, &desc);
    }
    let idx_id = bcx
        .declare_data(
            &format!("__luna_aot_proto_idx_{hex}"),
            Linkage::Local,
            false,
            false,
        )
        .expect("declare_data proto idx");
    if defined_aot_data.insert(idx_id) {
        let mut desc = DataDescription::new();
        desc.define(Box::new([0u8; 16]));
        desc.set_custom_section(&aot_data_section(
            &bcx.target_triple(),
            "luna_proto_idx",
            ".lt_prix",
        ));
        desc.set_align(8);
        let hash_gv = bcx.declare_data_in_data(hash_id, &mut desc);
        let slot_gv = bcx.declare_data_in_data(slot_id, &mut desc);
        desc.write_data_addr(0, hash_gv, 0);
        desc.write_data_addr(8, slot_gv, 0);
        let _ = bcx.define_data(idx_id, &desc);
    }
    let slot_gv = bcx.declare_data_in_func(slot_id);
    let slot_addr = bcx.symbol_value(types::I64, slot_gv);
    bcx.ins()
        .load(types::I64, MemFlagsData::trusted(), slot_addr, 0)
}
