-- Argument checks, lexer and parser messages as a script named
-- "@user_script" sees them (Redis's chunk name). A missing argument is
-- "no value" (lua_type == LUA_TNONE), a nil one is "nil". Lexer and
-- parser messages name the token as each dialect's luaX_token2str /
-- txtToken does ('<eof>' and '<name>' quoted in 5.1 and from 5.3 on,
-- bare in 5.2). In 5.1 goto is an ordinary name.
local load = loadstring or load
local function run(src)
  local f, m = load(src, "@user_script")
  if not f then print("compile", m) return end
  print("run", select(2, pcall(f)))
end
local function call(name, ...)
  local ok, f = pcall(load("return " .. name))
  if ok and f then print(name, select('#', ...), select(2, pcall(f, ...))) end
end
run("string.rep()")
run("string.rep(nil)")
run("string.rep('x', nil)")
run("string.sub()")
run("string.char(nil)")
run("string.byte()")
run("math.floor()")
run("math.max()")
run("table.concat()")
run("table.insert()")
run("setmetatable()")
run("setmetatable({})")
run("tostring()")
run("type()")
run("rawget({})")
run("rawset({}, 1)")
run("select()")
run("ipairs()")
run("tonumber()")
run("tonumber('1', nil)")
run("coroutine.resume()")
run("string.format()")
run("string.format('%d')")
run("string.format('%d', nil)")
-- string.rep and string.sub check their arguments in separate statements;
-- functions that pass several checks as the arguments of one C call
-- (math.fmod, bit32.lshift, package.searchpath, ...) are left out, since
-- which one fails first depends on the C compiler that built PUC
for _, n in ipairs({"string.rep", "string.sub", "string.byte", "table.concat"}) do
  call(n)
  call(n, nil)
  call(n, "x", nil)
  call(n, nil, "x")
end
run('return "unfinished')
run("return 'abc")
run('return "abc\ndef"')
run("return [[abc")
run("return [==[abc")
run("--[[ x")
run("return 1e")
run("return 0x")
run("return 3..4")
run('return "\\q"')
run('return "a\\300"')
run('return "\\x4"')
run('return "\\u{110000000}"')
run("x = ~ 1")
run("x = @")
run("x = $")
run("x = 1 ..")
run("x = 1 + ")
run("\n\nfor")
run("for 1")
run("for i = 1 do end")
run("for a, b do end")
run("local")
run("local 1")
run("function")
run("function f(")
run("function f(1) end")
run("x = {")
run("x = (1")
run("if x then")
run("if x")
run("while true")
run("repeat until")
run("return return")
run("f(")
run("a.b:c")
run("a.1 = 2")
run("x = }")
run("x = 1 == == 2")
run("x = 3 x")
run("::a:: ::a::")
run("break")
run("local function f() return ... end")
run("goto x")
run("goto = 2 return goto")
run("local goto = 1 return goto")
run("local t = {goto = 1} return t.goto")
run("function goto() return 7 end return goto()")
run("local function f(goto) return goto end return f(3)")
run("return type(function() local x <const> = 1 end)")
run("local x <foo> = 1")
run("x = 'a\\z  b'")
run("return 0x1p4")
run("return 1 // 2")
run("return 1 & 2")
