-- Lexer errors quote PUC's lex buffer as the near-token: the string
-- read so far (delimiter included, escapes half-decoded as each
-- dialect leaves them), the numeral as scanned, or <eof>.
local ld = loadstring or load
local function e(src)
  local f, msg = ld(src, "=c")
  print(f and "ok" or msg)
end
e([[x = "abc\q"]])
e([[x = "ab\qcd"]])
e([[x = "\256"]])
e([[x = "\xZZ"]])
e([[x = "\x5"]])
e([[x = "\u{48"]])
e([[x = "\u48"]])
e([[x = "\u{}"]])
e([[x = "\u{80000000}"]])
e("x = 'abc\nd'")
e("x = 'abc")
e("x = [==[abc]=]")
e("--[[ abc")
e("x = 3x")
e("x = 0xg")
e("x = 08z")
e("x = 1 2.5e3")
e("x = 1 'a\\tb'")
e("x = 1 [==[a\nb]==]")
e("return 0x1p4 == 16")
e("return 'a\\z\n  b'")
e("x = \1")
e("x = \0")
e("local $ = 1")
e("x = {1 @}")
e("return 1 & 2")
