//! The auxiliary library (`lauxlib.h`) and `lua_pushfstring`: written in C
//! on top of the public API, as PUC writes them (`csrc/aux*.c`), so their
//! stack effects are PUC's. Every function is C; this module only exports
//! their names.

c_exports! {
    lua_pushfstring => luna_c_lua_pushfstring,
    lua_pushvfstring => luna_c_lua_pushvfstring,
    luaL_where => luna_c_luaL_where,
    luaL_error => luna_c_luaL_error,
    luaL_argerror => luna_c_luaL_argerror,
    luaL_typeerror => luna_c_luaL_typeerror,
    luaL_typerror => luna_c_luaL_typerror,
    luaL_checklstring => luna_c_luaL_checklstring,
    luaL_optlstring => luna_c_luaL_optlstring,
    luaL_checknumber => luna_c_luaL_checknumber,
    luaL_optnumber => luna_c_luaL_optnumber,
    luaL_checkinteger => luna_c_luaL_checkinteger,
    luaL_optinteger => luna_c_luaL_optinteger,
    luaL_checkunsigned => luna_c_luaL_checkunsigned,
    luaL_optunsigned => luna_c_luaL_optunsigned,
    luaL_checkoption => luna_c_luaL_checkoption,
    luaL_checkstack => luna_c_luaL_checkstack,
    luaL_checktype => luna_c_luaL_checktype,
    luaL_checkany => luna_c_luaL_checkany,
    luaL_traceback => luna_c_luaL_traceback,
    luaL_newmetatable => luna_c_luaL_newmetatable,
    luaL_setmetatable => luna_c_luaL_setmetatable,
    luaL_testudata => luna_c_luaL_testudata,
    luaL_checkudata => luna_c_luaL_checkudata,
    luaL_getmetafield => luna_c_luaL_getmetafield,
    luaL_callmeta => luna_c_luaL_callmeta,
    luaL_len => luna_c_luaL_len,
    luaL_tolstring => luna_c_luaL_tolstring,
    luaL_getsubtable => luna_c_luaL_getsubtable,
    luaL_requiref => luna_c_luaL_requiref,
    luaL_setfuncs => luna_c_luaL_setfuncs,
    luaL_ref => luna_c_luaL_ref,
    luaL_unref => luna_c_luaL_unref,
    luaL_fileresult => luna_c_luaL_fileresult,
    luaL_execresult => luna_c_luaL_execresult,
    luaL_checkversion_ => luna_c_luaL_checkversion_,
    luna_checkversion_52 => luna_c_luna_checkversion_52,
    luaL_buffinit => luna_c_luaL_buffinit,
    luaL_buffinitsize => luna_c_luaL_buffinitsize,
    luaL_prepbuffsize => luna_c_luaL_prepbuffsize,
    luaL_prepbuffer => luna_c_luaL_prepbuffer,
    luaL_addlstring => luna_c_luaL_addlstring,
    luaL_addstring => luna_c_luaL_addstring,
    luaL_addvalue => luna_c_luaL_addvalue,
    luaL_pushresult => luna_c_luaL_pushresult,
    luaL_pushresultsize => luna_c_luaL_pushresultsize,
    luaL_addgsub => luna_c_luaL_addgsub,
    luaL_gsub => luna_c_luaL_gsub,
    luna_buffinit_51 => luna_c_luna_buffinit_51,
    luna_prepbuffer_51 => luna_c_luna_prepbuffer_51,
    luna_addlstring_51 => luna_c_luna_addlstring_51,
    luna_addstring_51 => luna_c_luna_addstring_51,
    luna_addvalue_51 => luna_c_luna_addvalue_51,
    luna_pushresult_51 => luna_c_luna_pushresult_51,
    luaL_loadfilex => luna_c_luaL_loadfilex,
    luaL_loadfile => luna_c_luaL_loadfile,
    luaL_loadbufferx => luna_c_luaL_loadbufferx,
    luaL_loadbuffer => luna_c_luaL_loadbuffer,
    luaL_loadstring => luna_c_luaL_loadstring,
}
