-- v2.10 CORPUS: string.format precision variants.
print(string.format("%d", 42))
print(string.format("%5d", 42))
print(string.format("%-5d|", 42))
print(string.format("%05d", 42))
print(string.format("%+d", 42))
print(string.format("%+d", -42))
print(string.format("%s", "hi"))
print(string.format("%10s|", "hi"))
print(string.format("%-10s|", "hi"))
print(string.format("%.3s", "hello"))
print(string.format("%x", 255))
print(string.format("%X", 255))
print(string.format("%o", 8))
print(string.format("%%"))
print(string.format("%q", 'he said "hi"'))
