//! The per-file assert-coverage report.

use super::*;

/// Write the coverage report into the workspace's `target/` directory,
/// resolved against the luna-core manifest dir.
///
/// Emits one Markdown table with one row per file (sorted by hit-rate
/// ascending so low-coverage files surface at the top) plus aggregate
/// totals. Files below 80% hit-rate get a `[WARN]` tag and a stderr
/// notice with a hint that a `_port` / `_soft` / `_noposix` gate is
/// likely skipping body.
pub(super) fn write_coverage_report(coverage: &[FileCoverage]) -> std::io::Result<()> {
    // CARGO_MANIFEST_DIR for luna-core is `<workspace>/crates/luna-core`,
    // so the report lands in the workspace's `target/` regardless of
    // whether we run from the main checkout or a worktree.
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("CARGO_MANIFEST_DIR has at least 2 ancestors");
    let dest_dir = workspace_root.join("target");
    std::fs::create_dir_all(&dest_dir)?;
    let dest = dest_dir.join("official-assert-coverage.md");

    // Aggregate. `wrapper_skipped` files are counted separately so the
    // ge80/lt80 buckets reflect only files where the wrapper actually
    // ran.
    let total_files = coverage.len();
    let mut total_asserts: i64 = 0;
    let mut total_hits: i64 = 0;
    let mut ge80 = 0usize;
    let mut lt80 = 0usize;
    let mut zero_total = 0usize;
    let mut skipped = 0usize;
    for c in coverage {
        total_asserts += c.total;
        total_hits += c.hit;
        if c.wrapper_skipped {
            skipped += 1;
        } else if c.total == 0 {
            zero_total += 1;
            lt80 += 1;
        } else {
            let rate = (c.hit as f64) / (c.total as f64);
            if rate >= 0.80 {
                ge80 += 1;
            } else {
                lt80 += 1;
            }
        }
    }

    // Sort by hit-rate ascending; files with total==0 sort first (rate
    // treated as -1 for sort purposes so they bubble up).
    let mut rows: Vec<&FileCoverage> = coverage.iter().collect();
    rows.sort_by(|a, b| {
        let ra = if a.total == 0 {
            -1.0
        } else {
            (a.hit as f64) / (a.total as f64)
        };
        let rb = if b.total == 0 {
            -1.0
        } else {
            (b.hit as f64) / (b.total as f64)
        };
        ra.partial_cmp(&rb)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.file.cmp(&b.file))
    });

    let mut out = String::new();
    out.push_str("# official suite assert-coverage report\n\n");
    out.push_str("Auto-generated by `crates/luna-core/tests/official_run.rs`.\n");
    out.push_str("Re-generate with `cargo test -p luna-core --test official_run`.\n\n");
    out.push_str("## Methodology\n\n");
    out.push_str("Each PUC chunk is prepended with a single-line Lua snippet that\n");
    out.push_str("wraps `_G.assert` to bump `__luna_assert_total` on every call and\n");
    out.push_str("`__luna_assert_hit` when the first argument is truthy. After the\n");
    out.push_str("chunk completes (or errors) the counters are read back from the\n");
    out.push_str("Vm globals.\n\n");
    out.push_str("- `total` — number of `assert(...)` calls actually reached\n");
    out.push_str("- `hit`   — of those, how many had a truthy first argument\n");
    out.push_str("- `rate`  — `hit / total` (100% means every reached assert\n");
    out.push_str("  passed; `< 100%` would indicate a failed-but-pcall'd assert)\n\n");
    out.push_str("**Note**: `rate` is *not* coverage relative to in-source\n");
    out.push_str("`assert(...)` calls — it is **reached / executed** asserts only.\n");
    out.push_str("Files with very low `total` relative to in-source counts are the\n");
    out.push_str("ones to investigate (a `_port` / `_soft` / `_noposix` gate is\n");
    out.push_str("likely skipping a big block of asserts).\n\n");
    out.push_str("## Aggregate\n\n");
    out.push_str(&format!("- Total PUC files exercised: **{total_files}**\n"));
    out.push_str(&format!("- Total asserts reached: **{total_asserts}**\n"));
    out.push_str(&format!("- Total asserts passing: **{total_hits}**\n"));
    out.push_str(&format!(
        "- Wrapper-skipped files (assert/debug introspection): **{skipped}**\n"
    ));
    out.push_str(&format!(
        "- Of instrumented files, `rate >= 80%`: **{ge80}**\n"
    ));
    out.push_str(&format!(
        "- Of instrumented files, `rate <  80%`: **{lt80}** (of which `total == 0`: {zero_total})\n\n"
    ));
    out.push_str("## Per-file (sorted by rate ascending)\n\n");
    out.push_str("| version | file | total | hit | rate | status |\n");
    out.push_str("|---|---|---:|---:|---:|---|\n");
    for c in &rows {
        let rate_str = if c.total == 0 {
            "—".to_string()
        } else {
            format!("{:.1}%", (c.hit as f64) / (c.total as f64) * 100.0)
        };
        let status = if c.wrapper_skipped {
            "SKIPPED: wrapper would break assert/debug introspection".to_string()
        } else if let Some(err) = &c.error {
            format!("ERROR: {}", err.chars().take(80).collect::<String>())
        } else if c.total == 0 {
            "WARN: 0 asserts reached".to_string()
        } else if (c.hit as f64) / (c.total as f64) < 0.80 {
            "WARN: < 80% hit-rate".to_string()
        } else {
            "ok".to_string()
        };
        out.push_str(&format!(
            "| {:?} | `{}` | {} | {} | {} | {} |\n",
            c.version, c.file, c.total, c.hit, rate_str, status
        ));
    }
    out.push_str("\n## Skip-gate hints\n\n");
    out.push_str("Files that consistently report a low `total` across dialects are\n");
    out.push_str("guarded by one of the harness gates set in `run_file`:\n\n");
    out.push_str("- `attrib.lua` — `_port=true` (skips `package.loadlib` C-library\n");
    out.push_str("  block, lines ~79-356)\n");
    out.push_str("- `main.lua`   — `_port=true` (skips `os.execute` / `arg` /\n");
    out.push_str("  popen sub-invocation block; 5.1 also has a top-level early\n");
    out.push_str("  return shim)\n");
    out.push_str("- `big.lua`, `verybig.lua` — `_soft=true` (skips multi-MB\n");
    out.push_str("  synthesized-program section)\n");
    out.push_str("- `files.lua` — `_port=true` + `_noposix=true` (skips\n");
    out.push_str("  popen/execute/`io.tmpfile`-via-`arg` block)\n\n");
    out.push_str("Counter-clobber risk: the harness wrapper sits at file scope; if\n");
    out.push_str("a PUC file later rebinds `_G.assert` itself, asserts that run\n");
    out.push_str("through the rebound `_G.assert` while the original is shadowed\n");
    out.push_str("go uncounted. A grep of `tests/official/` for `_G.assert =`\n");
    out.push_str("returned no matches, so this is not believed to affect any file\n");
    out.push_str("in the current suite.\n\n");
    out.push_str("## Wrapper-skip list\n\n");
    out.push_str("Two test files run **without** the assert-counter wrapper because\n");
    out.push_str("they introspect `assert` / `debug` behaviour the wrapper cannot\n");
    out.push_str("faithfully replicate:\n\n");
    out.push_str("- `errors.lua` — `pcall(assert)` (zero args) checks the error\n");
    out.push_str("  message contains `\"value expected\"`, which is the C-side\n");
    out.push_str("  `luaL_checkany` phrasing. The pure-Lua wrapper would emit\n");
    out.push_str("  `\"assertion failed!\"` instead.\n");
    out.push_str("- `db.lua`  — installs a `debug.sethook(\"l\")` line hook against\n");
    out.push_str("  a chunk loaded without debug info and asserts the hook never\n");
    out.push_str("  fires. The wrapper is a Lua function *with* debug info, so\n");
    out.push_str("  the line hook would fire on its body.\n\n");
    out.push_str("These two are reported with `total = 0` and status `SKIPPED:`\n");
    out.push_str("in the per-file table. They still run end-to-end under the\n");
    out.push_str("normal gate, just without coverage instrumentation.\n");

    std::fs::write(&dest, out)?;
    Ok(())
}
